name: FormsFeeder CI

on: 
  push:
    paths:
    - '**'
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11 for Shared Runner
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

      # The plugins prokject has a maven plugin misbehaves, so you need to clean before each build,
      # othwewise the PF4J plugin properties do not get written to the jar's manifest.
    - name: Clean the plugins
      run: mvn -B clean --file formsfeeder.plugins
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build with Maven
      run: mvn -B package -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
